server:
  port: 7071 #端口号

spring:
  datasource:
    password: 217812.com #数据库用户名
    username: root #数据库密码
    url: jdbc:mysql://localhost:3306/obtain-employee?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: employee-service #项目名称
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

#redis相关配置
su:
  redis:
#    password: root  #redis密码
    address: localhost:6379
    database: 0

  es:
    host: 43.139.206.205
    port: 9200

#swagger文档相关配置
  document:
    title: employee-service #swagger网站名称
    description: 服务文档 #swagger文档描述
    username: swt  #文档用户名
    email: xx  #邮箱
    enable: true  #是否开启swagger文档，true开启
    scanPacket: com.su #扫描的包

#邮箱发送验证码配置
msm:
  email: 2178127391@qq.com
  host: smtp.qq.com
  port: 587
  password: ygpzxmggwfgtdjad




